server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Betting_Data
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
logging.level.org.hibernate.SQL : DEBUG
logging.level.java.io.ObjectInputStream : DEBUG